---
# tasks file for mpd

- name: install mpd
  apt:
    name: mpd
    state: present
    update_cache: yes

- name: Generate MPD configuration file
  template:
    dest: "{{ mpd_conf }}"
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0644
    src: "{{ mpd_conf_src }}"
  notify: Restart MPD
