---
# tasks file for mpd
- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null ; do sleep $[ ( $RANDOM % 10 )  + 1 ]s ; done
  args:
    executable: /bin/bash
  changed_when: false

- name: install mpd packages
  apt:
    name:
      - mpd
      - mpc
    state: present
    update_cache: yes

- name: create mpd_music_directory
  file:
    name: "{{ mpd_music_directory }}"
    state: directory
    mode: u=rwX,g=rwX,o=rwX
    recurse: true

- name: get mountpoint of music directory
  shell: df "{{ mpd_music_directory }}" | awk 'NR==2{print $NF}'
  register: musicdir_mount
  changed_when: false

- name: get fstype of musicdir_mount
  set_fact:
    musicdir_fstype: "{{ item.fstype }}"
  loop: "{{ ansible_mounts }}"
  when: item.mount == musicdir_mount.stdout

- name: set music dir owner/group
  file:
    name: "{{ mpd_music_directory }}"
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    recurse: true
  when: musicdir_fstype != 'vfat'

- name: Generate MPD configuration file
  template:
    dest: "{{ mpd_conf }}"
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0644
    src: "{{ mpd_conf_src }}"
  notify: Restart MPD

- name: Ensure mpd service is running and enabled
  service:
    name: mpd
    state: started
    enabled: true
