---
# tasks file for ansible-install-mpd

- name: install mpd
  apt:
    name: mpd
    state: installed
    update_cache: yes

- name: Generate MPD configuration file
  template:
    dest: "{{ ansible_install_mpd_conf }}"
    owner: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    mode: 0644
    src: "{{ ansible_install_mpd_conf_src }}"
  notify: Restart MPD
