---
# tasks file for mpd
- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null ; do sleep $[ ( $RANDOM % 10 )  + 1 ]s ; done
  args:
    executable: /bin/bash

- name: install mpd packages
  apt:
    name:
      - mpd
      - mpc
    state: present
    update_cache: yes

- name: set permissions on music dir
  file:
    name: "{{ mpd_music_directory }}"
    state: directory
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0775
    recurse: true

- name: Generate MPD configuration file
  template:
    dest: "{{ mpd_conf }}"
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0644
    src: "{{ mpd_conf_src }}"
  notify: Restart MPD

- name: Ensure mpd service is running and enabled
  service:
    name: mpd
    state: started
    enabled: true
